# Generated by Django 3.2.9 on 2021-11-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='name',
        ),
    ]
