# Generated by Django 3.2.9 on 2021-11-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0003_user_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='Ip',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_data',
            name='host_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
