# Generated by Django 3.2.3 on 2021-11-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0004_auto_20211107_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='dateTime1',
            field=models.CharField(default='hi', max_length=100),
        ),
    ]
